import { promises as fs } from "node:fs";
import path from "node:path";
import type { EditorDoc, EditorDocSummary } from "./types";

// Editor docs live alongside generations / uploads under public/ so the
// thumbnail PNG can be served directly by Next.js. Each doc is a single
// JSON file plus an optional thumb.
const ROOT = path.join(process.cwd(), "public", "editor");
const DOCS_DIR = path.join(ROOT, "docs");
const THUMBS_DIR = path.join(ROOT, "thumbs");

// Doc ids generated by `newDoc()` look like `e_<base36>_<base36>`. We
// enforce that shape on every path lookup so a request with a crafted
// id (e.g. `../../etc/passwd`) can't escape the docs/thumbs dirs and
// can't read or overwrite arbitrary files. Hyphens are permitted for
// future-proofing only; underscores cover the current generator.
const SAFE_ID_RE = /^[A-Za-z0-9_-]{1,128}$/;

export function isValidEditorId(id: unknown): id is string {
  return typeof id === "string" && SAFE_ID_RE.test(id);
}

export async function ensureEditorDirs(): Promise<void> {
  await fs.mkdir(DOCS_DIR, { recursive: true });
  await fs.mkdir(THUMBS_DIR, { recursive: true });
}

function docPath(id: string): string {
  if (!isValidEditorId(id)) throw new Error("invalid editor id");
  return path.join(DOCS_DIR, `${id}.json`);
}

function thumbPath(id: string): string {
  if (!isValidEditorId(id)) throw new Error("invalid editor id");
  return path.join(THUMBS_DIR, `${id}.png`);
}

export async function saveEditorDoc(doc: EditorDoc): Promise<void> {
  await ensureEditorDirs();
  await fs.writeFile(docPath(doc.id), JSON.stringify(doc, null, 2), "utf-8");
}

export async function loadEditorDoc(id: string): Promise<EditorDoc | null> {
  try {
    const raw = await fs.readFile(docPath(id), "utf-8");
    return JSON.parse(raw) as EditorDoc;
  } catch {
    return null;
  }
}

export async function deleteEditorDoc(id: string): Promise<boolean> {
  let found = false;
  try {
    await fs.unlink(docPath(id));
    found = true;
  } catch {
    // already gone
  }
  await fs.unlink(thumbPath(id)).catch(() => {});
  return found;
}

// Saves a flattened thumbnail PNG (raw bytes, already encoded) so the
// dashboard listing can render previews without re-flattening on every
// request.
export async function saveEditorThumb(id: string, png: Buffer): Promise<string> {
  await ensureEditorDirs();
  await fs.writeFile(thumbPath(id), png);
  return `/editor/thumbs/${id}.png`;
}

export async function listEditorDocs(): Promise<EditorDocSummary[]> {
  await ensureEditorDirs();
  const files = await fs.readdir(DOCS_DIR).catch(() => [] as string[]);
  const out: EditorDocSummary[] = [];
  for (const f of files) {
    if (!f.endsWith(".json")) continue;
    try {
      const raw = await fs.readFile(path.join(DOCS_DIR, f), "utf-8");
      const doc = JSON.parse(raw) as EditorDoc;
      // The thumb is best-effort — checking existence with stat would
      // double the I/O on a large library, so we just point at the
      // expected URL and let the <img> tag 404 quietly if it's missing.
      out.push({
        id: doc.id,
        name: doc.name,
        createdAt: doc.createdAt,
        updatedAt: doc.updatedAt,
        thumbUrl: `/editor/thumbs/${doc.id}.png`,
        width: doc.canvas.width,
        height: doc.canvas.height,
      });
    } catch {
      // Skip unreadable entries silently — same convention as the
      // generations/uploads listers.
    }
  }
  return out.sort((a, b) => b.updatedAt - a.updatedAt);
}
